version: '2'

services:
    wikiviz_backend:
        build: apps/backend/
        volumes:
            - ./apps/backend/:/usr/src/app
        
    wikiviz_frontend:
        build: apps/frontend/
        volumes:
            - ./apps/frontend/src:/usr/src/app/src
            - ./apps/frontend/build:/usr/src/app/build
        command: npm run build

    wikiviz_nginx:
        image: nginx:1-alpine
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        volumes_from:
            - wikiviz_frontend:ro
        links:
            - wikiviz_frontend
            - wikiviz_backend
        ports:
            - 80:80
